## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import random

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df = city_data_df.drop(["City_ID"], axis = 1)
city_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,ushuaia,AR,-54.8000,-68.3000,37.06,81,0,2.30,clear sky
1,castro,BR,-24.7911,-50.0119,63.07,73,99,5.59,light rain
2,barbacoas,CO,1.6715,-78.1398,85.24,67,86,4.65,light rain
3,vaini,TO,-21.2000,-175.2000,69.96,100,20,2.30,few clouds
4,barra patuca,HN,15.8000,-84.2833,81.91,83,97,11.99,overcast clouds
...,...,...,...,...,...,...,...,...,...
706,santo tomas,PH,14.1079,121.1414,77.25,97,100,2.91,light rain
707,comodoro rivadavia,AR,-45.8667,-67.5000,42.66,75,75,10.36,broken clouds
708,gimli,CA,50.6336,-96.9907,63.84,54,100,14.29,overcast clouds
709,vyartsilya,RU,62.1764,30.6930,58.26,95,100,8.63,overcast clouds
710,christchurch,NZ,-43.5333,172.6333,44.91,97,1,1.14,fog

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_desired_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_desired_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 80

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_desired_temp) &
                                       (city_data_df["Max Temp"] >= min_desired_temp)]
preferred_cities_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
8,caravelas,BR,-17.7125,-39.2481,78.19,65,66,6.91,broken clouds
11,atuona,PF,-9.8000,-139.0333,77.00,77,76,17.22,broken clouds
13,srem,PL,52.0887,17.0151,70.02,38,73,8.34,broken clouds
16,hasaki,JP,35.7333,140.8333,73.80,80,65,7.14,broken clouds
17,jiuquan,CN,39.7432,98.5174,79.20,25,100,5.32,overcast clouds
25,boksitogorsk,RU,59.4740,33.8485,74.95,59,87,8.48,overcast clouds
27,puerto ayora,EC,-0.7393,-90.3518,78.76,89,93,8.99,overcast clouds
29,faanui,PF,-16.4833,-151.7500,77.97,76,53,25.77,light rain
32,kapaa,US,22.0752,-159.3190,79.12,88,75,4.61,broken clouds
35,sao filipe,CV,14.8961,-24.4956,78.15,85,72,8.14,light rain

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City                   217
Country                216
Lat                    217
Lng                    217
Max Temp               217
Humidity               217
Cloudiness             217
Wind Speed             217
Current Description    217
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
8,caravelas,BR,-17.7125,-39.2481,78.19,65,66,6.91,broken clouds
11,atuona,PF,-9.8000,-139.0333,77.00,77,76,17.22,broken clouds
13,srem,PL,52.0887,17.0151,70.02,38,73,8.34,broken clouds
16,hasaki,JP,35.7333,140.8333,73.80,80,65,7.14,broken clouds
17,jiuquan,CN,39.7432,98.5174,79.20,25,100,5.32,overcast clouds
...,...,...,...,...,...,...,...,...,...
690,sept-iles,CA,50.2001,-66.3821,70.32,65,75,12.66,broken clouds
699,jiancheng,CN,30.3910,104.5491,78.57,86,6,1.97,clear sky
704,talavera,PH,15.6167,120.9333,74.95,92,100,3.49,moderate rain
705,matagami,CA,49.7502,-77.6328,75.31,69,75,18.41,broken clouds
706,santo tomas,PH,14.1079,121.1414,77.25,97,100,2.91,light rain

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
8,caravelas,BR,78.19,broken clouds,-17.7125,-39.2481,
11,atuona,PF,77.00,broken clouds,-9.8000,-139.0333,
13,srem,PL,70.02,broken clouds,52.0887,17.0151,
16,hasaki,JP,73.80,broken clouds,35.7333,140.8333,
17,jiuquan,CN,79.20,overcast clouds,39.7432,98.5174,
25,boksitogorsk,RU,74.95,overcast clouds,59.4740,33.8485,
27,puerto ayora,EC,78.76,overcast clouds,-0.7393,-90.3518,
29,faanui,PF,77.97,light rain,-16.4833,-151.7500,
32,kapaa,US,79.12,broken clouds,22.0752,-159.3190,
35,sao filipe,CV,78.15,light rain,14.8961,-24.4956,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
current_entry = 0
total_hotel_entries = len(hotel_df)

for index, row in hotel_df.iterrows():

    current_entry += 1
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    city = row["City"]
    country = row["Country"]
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        print(f"Entry {current_entry} out of {total_hotel_entries}")
        print(f"Looking for hotels near {city}, {country}")
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except Exception as e:
        print(f"Received the following error while looking for Hotels near {city}:")
        print(e)
        print("Hotel not found... skipping.")

Entry 1 out of 216
Looking for hotels near caravelas, BR
Entry 2 out of 216
Looking for hotels near atuona, PF
Entry 3 out of 216
Looking for hotels near srem, PL
Entry 4 out of 216
Looking for hotels near hasaki, JP
Entry 5 out of 216
Looking for hotels near jiuquan, CN
Entry 6 out of 216
Looking for hotels near boksitogorsk, RU
Entry 7 out of 216
Looking for hotels near puerto ayora, EC
Entry 8 out of 216
Looking for hotels near faanui, PF
Entry 9 out of 216
Looking for hotels near kapaa, US
Entry 10 out of 216
Looking for hotels near sao filipe, CV
Entry 11 out of 216
Looking for hotels near shingu, JP
Entry 12 out of 216
Looking for hotels near ponta do sol, PT
Entry 13 out of 216
Looking for hotels near cochrane, CA
Entry 14 out of 216
Looking for hotels near buarcos, PT
Entry 15 out of 216
Looking for hotels near arraial do cabo, BR
Entry 16 out of 216
Looking for hotels near tual, ID
Entry 17 out of 216
Looking for hotels near angoche, MZ
Entry 18 out of 216
Looking for hotels near lompoc, US
Entry 19 out of 216
Looking for hotels near guerrero negro, MX
Entry 20 out of 216
Looking for hotels near kawalu, ID
Entry 21 out of 216
Looking for hotels near dubrovytsya, UA
Entry 22 out of 216
Looking for hotels near nouadhibou, MR
Entry 23 out of 216
Looking for hotels near la ronge, CA
Entry 24 out of 216
Looking for hotels near lat yao, TH
Entry 25 out of 216
Looking for hotels near vila velha, BR
Entry 26 out of 216
Looking for hotels near naze, JP
Entry 27 out of 216
Looking for hotels near divnoye, RU
Entry 28 out of 216
Looking for hotels near ambilobe, MG
Entry 29 out of 216
Looking for hotels near buchanan, LR
Entry 30 out of 216
Looking for hotels near san quintin, MX
Entry 31 out of 216
Looking for hotels near mazamari, PE
Entry 32 out of 216
Looking for hotels near kieta, PG
Entry 33 out of 216
Looking for hotels near tebingtinggi, ID
Entry 34 out of 216
Looking for hotels near asau, RO
Entry 35 out of 216
Looking for hotels near lardos, GR
Entry 36 out of 216
Looking for hotels near oron, NG
Entry 37 out of 216
Looking for hotels near alofi, NU
Entry 38 out of 216
Looking for hotels near gorontalo, ID
Entry 39 out of 216
Looking for hotels near san cristobal, VE
Entry 40 out of 216
Looking for hotels near sunyani, GH
Entry 41 out of 216
Looking for hotels near sao joao da barra, BR
Entry 42 out of 216
Looking for hotels near takoradi, GH
Entry 43 out of 216
Looking for hotels near cabatuan, PH
Entry 44 out of 216
Looking for hotels near katsuura, JP
Entry 45 out of 216
Looking for hotels near lata, PT
Entry 46 out of 216
Looking for hotels near vila franca do campo, PT
Entry 47 out of 216
Looking for hotels near merauke, ID
Received the following error while looking for Hotels near merauke:
list index out of range
Hotel not found... skipping.
Entry 48 out of 216
Looking for hotels near honavar, IN
Entry 49 out of 216
Looking for hotels near tautira, PF
Entry 50 out of 216
Looking for hotels near torbay, CA
Entry 51 out of 216
Looking for hotels near bambous virieux, MU
Entry 52 out of 216
Looking for hotels near rock springs, US
Entry 53 out of 216
Looking for hotels near los llanos de aridane, ES
Entry 54 out of 216
Looking for hotels near saint-augustin, CA
Received the following error while looking for Hotels near saint-augustin:
list index out of range
Hotel not found... skipping.
Entry 55 out of 216
Looking for hotels near bengkulu, ID
Entry 56 out of 216
Looking for hotels near faranah, GN
Entry 57 out of 216
Looking for hotels near hobyo, SO
Entry 58 out of 216
Looking for hotels near avarua, CK
Entry 59 out of 216
Looking for hotels near ukiah, US
Entry 60 out of 216
Looking for hotels near north bend, US
Entry 61 out of 216
Looking for hotels near huicheng, CN
Entry 62 out of 216
Looking for hotels near colchester, GB
Entry 63 out of 216
Looking for hotels near dariba, IN
Entry 64 out of 216
Looking for hotels near nhulunbuy, AU
Entry 65 out of 216
Looking for hotels near isangel, VU
Entry 66 out of 216
Looking for hotels near tadine, NC
Received the following error while looking for Hotels near tadine:
list index out of range
Hotel not found... skipping.
Entry 67 out of 216
Looking for hotels near frolovo, RU
Entry 68 out of 216
Looking for hotels near msowero, TZ
Received the following error while looking for Hotels near msowero:
list index out of range
Hotel not found... skipping.
Entry 69 out of 216
Looking for hotels near port-cartier, CA
Entry 70 out of 216
Looking for hotels near puerto del rosario, ES
Entry 71 out of 216
Looking for hotels near maneadero, MX
Entry 72 out of 216
Looking for hotels near xuddur, SO
Entry 73 out of 216
Looking for hotels near bajil, YE
Entry 74 out of 216
Looking for hotels near poum, NC
Received the following error while looking for Hotels near poum:
list index out of range
Hotel not found... skipping.
Entry 75 out of 216
Looking for hotels near dingle, PH
Entry 76 out of 216
Looking for hotels near vao, NC
Entry 77 out of 216
Looking for hotels near lingyuan, CN
Entry 78 out of 216
Looking for hotels near saint-pierre, RE
Entry 79 out of 216
Looking for hotels near kota kinabalu, MY
Entry 80 out of 216
Looking for hotels near aitape, PG
Received the following error while looking for Hotels near aitape:
list index out of range
Hotel not found... skipping.
Entry 81 out of 216
Looking for hotels near lisa, RO
Entry 82 out of 216
Looking for hotels near temir, KZ
Received the following error while looking for Hotels near temir:
list index out of range
Hotel not found... skipping.
Entry 83 out of 216
Looking for hotels near petrykivka, UA
Entry 84 out of 216
Looking for hotels near odweyne, SO
Entry 85 out of 216
Looking for hotels near tura, IN
Entry 86 out of 216
Looking for hotels near sarny, UA
Entry 87 out of 216
Looking for hotels near moerai, PF
Entry 88 out of 216
Looking for hotels near chaozhou, CN
Entry 89 out of 216
Looking for hotels near auki, SB
Entry 90 out of 216
Looking for hotels near shimoda, JP
Entry 91 out of 216
Looking for hotels near salalah, OM
Entry 92 out of 216
Looking for hotels near kukes, AL
Entry 93 out of 216
Looking for hotels near padang, ID
Entry 94 out of 216
Looking for hotels near dodan, PH
Entry 95 out of 216
Looking for hotels near vrangel, RU
Entry 96 out of 216
Looking for hotels near san jose, US
Entry 97 out of 216
Looking for hotels near ribeira grande, PT
Entry 98 out of 216
Looking for hotels near tirschenreuth, DE
Entry 99 out of 216
Looking for hotels near angoram, PG
Received the following error while looking for Hotels near angoram:
list index out of range
Hotel not found... skipping.
Entry 100 out of 216
Looking for hotels near mandla, IN
Entry 101 out of 216
Looking for hotels near mahebourg, MU
Entry 102 out of 216
Looking for hotels near sal rei, CV
Entry 103 out of 216
Looking for hotels near axim, GH
Entry 104 out of 216
Looking for hotels near acari, PE
Entry 105 out of 216
Looking for hotels near porto novo, BJ
Entry 106 out of 216
Looking for hotels near mumford, GH
Entry 107 out of 216
Looking for hotels near tizapan el alto, MX
Entry 108 out of 216
Looking for hotels near cravo norte, CO
Entry 109 out of 216
Looking for hotels near kamenka, RU
Received the following error while looking for Hotels near kamenka:
list index out of range
Hotel not found... skipping.
Entry 110 out of 216
Looking for hotels near hoima, UG
Entry 111 out of 216
Looking for hotels near mons, BE
Entry 112 out of 216
Looking for hotels near wajima, JP
Entry 113 out of 216
Looking for hotels near santa rosa, PH
Entry 114 out of 216
Looking for hotels near quelimane, MZ
Entry 115 out of 216
Looking for hotels near erzin, TR
Entry 116 out of 216
Looking for hotels near yenagoa, NG
Entry 117 out of 216
Looking for hotels near asfi, MA
Entry 118 out of 216
Looking for hotels near biak, ID
Entry 119 out of 216
Looking for hotels near horsham, GB
Entry 120 out of 216
Looking for hotels near harper, LR
Entry 121 out of 216
Looking for hotels near souillac, MU
Entry 122 out of 216
Looking for hotels near kochubey, RU
Entry 123 out of 216
Looking for hotels near galesong, ID
Entry 124 out of 216
Looking for hotels near wajid, SO
Entry 125 out of 216
Looking for hotels near kimbe, PG

Entry 126 out of 216
Looking for hotels near semporna, MY
Entry 127 out of 216
Looking for hotels near half moon bay, US
Entry 128 out of 216
Looking for hotels near ponta delgada, PT
Entry 129 out of 216
Looking for hotels near sri aman, MY
Entry 130 out of 216
Looking for hotels near rambha, IN
Entry 131 out of 216
Looking for hotels near bellevue, US
Entry 132 out of 216
Looking for hotels near bairiki, KI
Entry 133 out of 216
Looking for hotels near labuhan, ID
Entry 134 out of 216
Looking for hotels near santa cruz, BO
Entry 135 out of 216
Looking for hotels near tanete, ID
Entry 136 out of 216
Looking for hotels near namatanai, PG
Entry 137 out of 216
Looking for hotels near nabire, ID
Entry 138 out of 216
Looking for hotels near rucheng, CN
Entry 139 out of 216
Looking for hotels near lagoa, PT
Entry 140 out of 216
Looking for hotels near fort nelson, CA
Entry 141 out of 216
Looking for hotels near sucua, EC
Entry 142 out of 216
Looking for hotels near mogadishu, SO
Entry 143 out of 216
Looking for hotels near kirakira, SB
Entry 144 out of 216
Looking for hotels near ambunti, PG
Entry 145 out of 216
Looking for hotels near wewak, PG
Entry 146 out of 216
Looking for hotels near qui nhon, VN
Entry 147 out of 216
Looking for hotels near otukpo, NG
Entry 148 out of 216
Looking for hotels near rochegda, RU
Received the following error while looking for Hotels near rochegda:
list index out of range
Hotel not found... skipping.
Entry 149 out of 216
Looking for hotels near ponnani, IN
Entry 150 out of 216
Looking for hotels near dayong, CN
Entry 151 out of 216
Looking for hotels near arbuzynka, UA
Received the following error while looking for Hotels near arbuzynka:
list index out of range
Hotel not found... skipping.
Entry 152 out of 216
Looking for hotels near quatre cocos, MU
Entry 153 out of 216
Looking for hotels near kanigoro, ID
Entry 154 out of 216
Looking for hotels near raigarh, IN
Entry 155 out of 216
Looking for hotels near port-gentil, GA
Entry 156 out of 216
Looking for hotels near burgeo, CA
Entry 157 out of 216
Looking for hotels near svetlogorsk, BY
Entry 158 out of 216
Looking for hotels near nanning, CN
Entry 159 out of 216
Looking for hotels near tamandare, BR
Entry 160 out of 216
Looking for hotels near vung tau, VN
Entry 161 out of 216
Looking for hotels near beidao, CN
Entry 162 out of 216
Looking for hotels near paka, MY
Entry 163 out of 216
Looking for hotels near tateyama, JP
Entry 164 out of 216
Looking for hotels near pacific grove, US
Entry 165 out of 216
Looking for hotels near buala, SB
Entry 166 out of 216
Looking for hotels near inhambane, MZ
Entry 167 out of 216
Looking for hotels near along, IN
Entry 168 out of 216
Looking for hotels near sibolga, ID
Entry 169 out of 216
Looking for hotels near vanimo, PG
Entry 170 out of 216
Looking for hotels near maumere, ID
Entry 171 out of 216
Looking for hotels near impfondo, CG
Entry 172 out of 216
Looking for hotels near aborlan, PH
Entry 173 out of 216
Looking for hotels near talara, PE
Entry 174 out of 216
Looking for hotels near borovichi, RU
Entry 175 out of 216
Looking for hotels near tabou, CI
Entry 176 out of 216
Looking for hotels near bambanglipuro, ID
Entry 177 out of 216
Looking for hotels near etampes, FR
Entry 178 out of 216
Looking for hotels near ca mau, VN
Entry 179 out of 216
Looking for hotels near barabai, ID
Entry 180 out of 216
Looking for hotels near zolotukhino, RU
Entry 181 out of 216
Looking for hotels near noumea, NC
Entry 182 out of 216
Looking for hotels near ahtopol, BG
Entry 183 out of 216
Looking for hotels near abu zabad, SD
Entry 184 out of 216
Looking for hotels near chavantes, BR
Entry 185 out of 216
Looking for hotels near lorengau, PG
Entry 186 out of 216
Looking for hotels near szany, HU
Entry 187 out of 216
Looking for hotels near chifeng, CN
Entry 188 out of 216
Looking for hotels near manta, EC
Entry 189 out of 216
Looking for hotels near meulaboh, ID
Entry 190 out of 216
Looking for hotels near praia da vitoria, PT
Entry 191 out of 216
Looking for hotels near luau, AO
Entry 192 out of 216
Looking for hotels near conakry, GN
Entry 193 out of 216
Looking for hotels near chapais, CA
Entry 194 out of 216
Looking for hotels near saiha, IN
Entry 195 out of 216
Looking for hotels near tabuk, PH
Entry 196 out of 216
Looking for hotels near srandakan, ID
Entry 197 out of 216
Looking for hotels near yarada, IN
Entry 198 out of 216
Looking for hotels near port moresby, PG
Entry 199 out of 216
Looking for hotels near winneba, GH
Entry 200 out of 216
Looking for hotels near shieli, KZ
Entry 201 out of 216
Looking for hotels near havre-saint-pierre, CA
Entry 202 out of 216
Looking for hotels near waingapu, ID
Entry 203 out of 216
Looking for hotels near prado, BR
Entry 204 out of 216
Looking for hotels near narasannapeta, IN
Entry 205 out of 216
Looking for hotels near raga, SS
Received the following error while looking for Hotels near raga:
list index out of range
Hotel not found... skipping.
Entry 206 out of 216
Looking for hotels near novyy yegorlyk, RU
Received the following error while looking for Hotels near novyy yegorlyk:
list index out of range
Hotel not found... skipping.
Entry 207 out of 216
Looking for hotels near severnyy, RU
Entry 208 out of 216
Looking for hotels near tarakan, ID
Entry 209 out of 216
Looking for hotels near saint anthony, US
Entry 210 out of 216
Looking for hotels near semenivka, UA
Received the following error while looking for Hotels near semenivka:
list index out of range
Hotel not found... skipping.
Entry 211 out of 216
Looking for hotels near ecoporanga, BR
Entry 212 out of 216
Looking for hotels near sept-iles, CA
Entry 213 out of 216
Looking for hotels near jiancheng, CN
Entry 214 out of 216
Looking for hotels near talavera, PH
Entry 215 out of 216
Looking for hotels near matagami, CA
Entry 216 out of 216
Looking for hotels near santo tomas, PH

In [11]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"] != "")]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
8,caravelas,BR,78.19,broken clouds,-17.7125,-39.2481,Pousada dos Navegantes
11,atuona,PF,77.00,broken clouds,-9.8000,-139.0333,Villa Enata
13,srem,PL,70.02,broken clouds,52.0887,17.0151,L'Ascada. Hotel
16,hasaki,JP,73.80,broken clouds,35.7333,140.8333,Inubosaki Kanko Hotel
17,jiuquan,CN,79.20,overcast clouds,39.7432,98.5174,Jiuquan Hotel
...,...,...,...,...,...,...,...
690,sept-iles,CA,70.32,broken clouds,50.2001,-66.3821,Comfort Inn
699,jiancheng,CN,78.57,clear sky,30.3910,104.5491,Jianyang Celebrity City Hotel
704,talavera,PH,74.95,moderate rain,15.6167,120.9333,R&G's Resort
705,matagami,CA,75.31,broken clouds,49.7502,-77.6328,Motel Le Caribou
706,santo tomas,PH,77.25,light rain,14.1079,121.1414,Microtel by Wyndham Batangas

In [14]:
# 8a. Create the output File (CSV)
output_data_file =  "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [15]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [19]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(
    center=(30.0, 31.0), 
    zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))